# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Albert/Desktop/logic  design/Final link/Final vivado/FinalProject.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Albert/Desktop/logic  design/Final link/Final vivado/FinalProject.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Albert/Desktop/logic  design/Final link/Final vivado/src/don't touch/ssDisplayer.v}
  {C:/Users/Albert/Desktop/logic  design/Final link/Final vivado/src/don't touch/ssDecoder.v}
  {C:/Users/Albert/Desktop/logic  design/Final link/Final vivado/src/don't touch/SevenSegment.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Albert/Desktop/logic  design/Final link/Final vivado/src/don't touch/PortDefine_basys3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Albert/Desktop/logic  design/Final link/Final vivado/src/don't touch/PortDefine_basys3.xdc}}]


synth_design -top SevenSegment -part xc7a35tcpg236-1


write_checkpoint -force -noxdef SevenSegment.dcp

catch { report_utilization -file SevenSegment_utilization_synth.rpt -pb SevenSegment_utilization_synth.pb }
