# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Albert/Desktop/logic  design/lab_hw6/lab_hw6.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Albert/Desktop/logic  design/lab_hw6/lab_hw6.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Albert/Desktop/logic  design/lab_hw6/LAB6_2.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Albert/Desktop/logic  design/lab_hw6/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Albert/Desktop/logic  design/lab_hw6/Basys3_Master.xdc}}]


synth_design -top LAB6 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef LAB6.dcp

catch { report_utilization -file LAB6_utilization_synth.rpt -pb LAB6_utilization_synth.pb }
